package Learning;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.support.ui.Select;
public class Adactin_Task {

	public static void main(String[] args) throws InterruptedException {
		System.setProperty("webdriver.edge.driver", 
				"C:\\Users\\sangeetha\\eclipse-workspace\\Selenium_Concepts\\Driver\\msedgedriver.exe");
		WebDriver wd = new EdgeDriver();
		wd.get("http://adactinhotelapp.com/");
		wd.manage().window().maximize();
		Thread.sleep(3000);
		wd.findElement(By.xpath("//a[text()='New User Register Here']")).click();
		Thread.sleep(3000);
		wd.findElement(By.id("username")).sendKeys("Sangitha04");
		Thread.sleep(2000);
		wd.findElement(By.id("password")).sendKeys("123456789");
		Thread.sleep(2000);
		wd.findElement(By.id("re_password")).sendKeys("123456789");
		Thread.sleep(2000);
		wd.findElement(By.id("full_name")).sendKeys("Sangeetha_Hariharan");
		Thread.sleep(2000);
		wd.findElement(By.id("email_add")).sendKeys("sanzisr@gmail.com");
		Thread.sleep(10000);
		wd.findElement(By.id("tnc_box")).click();
		Thread.sleep(2000);
		wd.findElement(By.id("Submit")).click();
		Thread.sleep(20000);
		wd.findElement(By.xpath("//a[text()='Click here to login']")).click();
		Thread.sleep(3000);
		wd.findElement(By.id("username")).sendKeys("Sangitha04");
		Thread.sleep(2000);
		wd.findElement(By.id("password")).sendKeys("123456789");
		Thread.sleep(2000);
		wd.findElement(By.id("login")).click();
		Thread.sleep(2000);
		WebElement loc = wd.findElement(By.id("location"));
		Select s1 = new Select(loc);
		s1.selectByIndex(5);
		Thread.sleep(2000);
		WebElement hotel = wd.findElement(By.id("hotels"));
		Select s2 = new Select(hotel);
		s2.selectByValue("Hotel Sunshine");
		Thread.sleep(2000);
		WebElement room = wd.findElement(By.id("room_type"));
		Select s3 = new Select(room);
		s3.selectByValue("Super Deluxe");
		Thread.sleep(2000);
		WebElement nos = wd.findElement(By.id("room_nos"));
		Select s4 = new Select(nos);
		s4.selectByVisibleText("2 - Two");
		Thread.sleep(2000);
		WebElement adult = wd.findElement(By.id("adult_room"));
		Select s5 = new Select(adult);
		s5.selectByValue("2");
		Thread.sleep(2000);
		WebElement child = wd.findElement(By.id("child_room"));
		Select s6 = new Select(child);
		s6.selectByVisibleText("0 - None");
		wd.findElement(By.id("Submit")).click();
		WebElement radio = wd.findElement(By.id("radiobutton_0"));
		boolean selected = radio.isSelected();
		if (selected==false) {
			radio.click();
		}
		Thread.sleep(3000);
		wd.findElement(By.name("continue")).click();
		Thread.sleep(3000);
		JavascriptExecutor js = (JavascriptExecutor) wd;
		js.executeScript("window.scrollBy(0,500)", "");
		Thread.sleep(2000);
		wd.findElement(By.name("first_name")).sendKeys("Sangeetha");
		Thread.sleep(2000);
		wd.findElement(By.name("last_name")).sendKeys("Hariharan");
		Thread.sleep(2000);
		wd.findElement(By.id("address")).sendKeys("20,Street-01,Area,Chennai.");
		Thread.sleep(2000);
		wd.findElement(By.id("cc_num")).sendKeys("0123456789012345");
		Thread.sleep(2000);
		WebElement cc = wd.findElement(By.id("cc_type"));
		Select s7 = new Select(cc);
		s7.selectByValue("MAST");
		Thread.sleep(2000);
		WebElement exp = wd.findElement(By.id("cc_exp_month"));
		Select s8 = new Select(exp);
		s8.selectByVisibleText("August");
		Thread.sleep(2000);
		WebElement yr = wd.findElement(By.id("cc_exp_year"));
		Select s9 = new Select(yr);
		s9.selectByVisibleText("2022");
		Thread.sleep(2000);
		wd.findElement(By.id("cc_cvv")).sendKeys("294");
		Thread.sleep(2000);
		wd.findElement(By.id("book_now")).click();
		Thread.sleep(10000);
		WebElement down = wd.findElement(By.xpath("//a[text()='Adactin.com']"));
		js.executeScript("arguments[0].scrollIntoView();", down);
		Thread.sleep(5000);
		wd.findElement(By.id("my_itinerary")).click();
		Thread.sleep(3000);
		wd.findElement(By.id("logout")).click();	
	}
	}